CREATE TABLE diabetes_results (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  monthName TEXT NOT NULL,
  mealName TEXT NOT NULL,
  result INTEGER,
  resultDate TIMESTAMPTZ DEFAULT now() NOT NULL,
  monthid INTEGER REFERENCES diabetes_months(id) ON DELETE CASCADE NOT NULL,
  dailyDescription TEXT NOT NULL,
  diabetesType TEXT NOT NULL
);

-- ALTER TABLE diabetes_results
--   ADD COLUMN
--     date_taken

-- CREATE TABLE diabetes_results (
--   id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
--   monthName TEXT NOT NULL,
--   mealName TEXT NOT NULL,
--   result INTEGER,
--   date TIMESTAMPTZ DEFAULT now() NOT NULL,hs(id) ON DELETE CASCADE NOT NULL,
--   monthid INTEGER REFERENCES diabetes_months(id) ON DELETE CASCADE NOT NULL,
--   description TEXT NOT NULL,
--   dtype TEXT NOT NULL
